---
- name: Configure Elasticsearch Kubernetes Deployment
  hosts: 
    - "{{ groups['kubernetes_masters'] | random }}"
  gather_facts: no
  vars:
    kubernetes_admin_user: kubeadm
    create_config_files: true
  roles:
    - role: elasticsearch_k8s_deployment
