---
- name: Create /etc/docker directory
  become: yes
  become_user: root
  file:
    path: /etc/docker
    state: directory

- name: Install daemon.json file
  become: yes
  become_user: root
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart_docker
