---

# This probably should not be installed on the masters, but a dedicated management node

- name: Install packages to manage Kubernetes with Ansible
  become: yes
  become_user: root
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - epel-release
    - python2-openshift
    - python2-pip
  tags:
    - dependency

- name: Install python modules to manage Kubernetes with Ansible
  become: yes
  become_user: root
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    extra_args: --trusted-host pypi.org --trusted-host files.pythonhosted.org
  loop:
    - { name: "importlib-metadata",  version: "2.0.0" }
    - { name: "configparser",        version: "3.5" }
    - { name: "zipp",                version: "0.5" }
    - { name: "kubernetes-validate", version: "1.11.2" }
    - { name: "pyrsistent",          version: "0.16.0" }
  tags:
    - dependency
