---
- name: Assemble Elasticsearch Master Node Configuration Info
  set_fact:
    elastic_master_vars: |
      {{ 
          elastic_master_vars | default([]) |
          combine( {hostvars[item].site: {
            'version': hostvars[item].elasticsearch_version,
            'site': hostvars[item].site,
            'namespace': hostvars[item].namespace,
            'cluster': hostvars[item].cluster,
            'master_volume': hostvars[item].elastic_master_volume,
            'master_replicas': hostvars[item].master_replicas
          }})
      }}
  loop: "{{ groups['elasticsearch'] }}"
  tags:
    - master

- name: Create Elasticsearch Master Service Configuration Files
  delegate_to: localhost
  template:
    src: templates/master-service.j2
    dest: configs/{{ site }}-master-service.yml
  vars:
    site: "{{ elastic_master_vars[item]['site'] }}"
    namespace: "{{ elastic_master_vars[item]['namespace'] }}"
  loop: "{{ elastic_master_vars.keys() | list }}"
  tags:
    - master
  when: create_config_files | bool

- name: Apply Elasticsearch Master Service Configuration
  become: yes
  become_user: "{{ kubernetes_admin_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'master-service.j2') }}"
    validate:
      fail_on_error: no
      strict: yes
  vars:
    site: "{{ elastic_master_vars[item]['site'] }}"
    namespace: "{{ elastic_master_vars[item]['namespace'] }}"
  loop: "{{ elastic_master_vars.keys() | list }}"
  tags:
    - master

- name: Create Elasticsearch Master ReplicaSet Configuration Files
  delegate_to: localhost
  template:
    src: templates/master-replicaset.j2
    dest: configs/{{ site }}-master-replicaset.yml
  vars:
    version: "{{ elastic_master_vars[item]['version'] }}"
    site: "{{ elastic_master_vars[item]['site'] }}"
    namespace: "{{ elastic_master_vars[item]['namespace'] }}"
    master_replicas: "{{ elastic_master_vars[item]['master_replicas'] }}"
    minimum_masters: "{{ (elastic_master_vars[item]['master_replicas'] / 2 + 1) | int }}"
    cluster: "{{ elastic_master_vars[item]['cluster'] }}"
  loop: "{{ elastic_master_vars.keys() | list }}"
  tags:
    - master
  when: create_config_files | bool

- name: Apply Elasticsearch Master ReplicaSet Configuration
  become: yes
  become_user: "{{ kubernetes_admin_user }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'master-replicaset.j2') }}"
    validate:
      fail_on_error: no
      strict: yes
  vars:
    version: "{{ elastic_master_vars[item]['version'] }}"
    site: "{{ elastic_master_vars[item]['site'] }}"
    namespace: "{{ elastic_master_vars[item]['namespace'] }}"
    master_replicas: "{{ elastic_master_vars[item]['master_replicas'] }}"
    minimum_masters: "{{ (elastic_master_vars[item]['master_replicas'] / 2 + 1) | int }}"
    cluster: "{{ elastic_master_vars[item]['cluster'] }}"
  loop: "{{ elastic_master_vars.keys() | list }}"
  tags:
    - master
